### ISSUE TITLE
test.pyを配置しないとBOOT.INIが読み込まれない

### ISSUE THREAD

**Issue by yukota** [aks3g/ai_mini_4wd_kit#1]
test.pyを配置しなかった場合、fatal_errorになり、結果としてBOOT.INIが読み込まれません。
src/script以下にtest.pyを置くか、test.pyがない場合fatalに落ちないようにしたほうがわかりやすいかと思います。

**Comment by aks3g** [comment]
期待通りの動きではない（BOOT.INIがtest.pyに依存するのはおかしい）ので修正します。

**Comment by aks3g** [comment]
こちら、すいませんコミット前に確認したはずがデバッグ中のコードが残っておりました。
https://github.com/aks3g/ai_mini_4wd_kit/commit/45d6fbbb8115bdc94f4985d53593735f37e6d077

こちらで修正済みです（お恥ずかしい）

**Comment by yukota** [comment]
Thank you!
