### ISSUE TITLE
fatal_error時にログが0で埋められる

### ISSUE THREAD

**Issue by yukota** [aks3g/ai_mini_4wd_kit#2]
__fatal_error時にすべて0で埋められた1MBほどのLOGが出力されれます。
test.pyを配置せず起動した時発生しました。

**Comment by aks3g** [comment]
すいません。こちらエラー時の処理の実装がおかしいですね。
1MBの0埋めファイルが出力されるのは期待通りで、一旦フラッシュ上に1MBのファイルを生成しておくことで、フラッシュへの書き込み速度を向上することを狙っています。
通常処理では、スクリプト実行が終わった時点でファイルサイズを切り詰めているのですが、fatal_errorでのハンドリングに失敗しています。こちら修正いたします。

**Comment by aks3g** [comment]
こちらの問題、
https://github.com/aks3g/ai_mini_4wd_kit/commit/397fed656ada02aa9ae12c15ee46a473bcba1de8

で修正しました。Fatalに落ちた後に、FatalメッセージをLOGに書き込んだのちにログファイルのサイズを切り詰める処理を入れたので、Fatalのメッセージも読めるようになります。

**Comment by yukota** [comment]
ありがとうございます。
