### ISSUE TITLE
MicroPythonからSDカードに対する書き込みができない

### ISSUE THREAD

**Issue by yukota** [aks3g/ai_mini_4wd_kit#5]
以下のようなコードを実行すると、writeでAttributeError: no such attributeが発生する。
```python
f = open("out.json", 'w')
f.write("aaaa")
f.close()
```

MicroPythonからSDカード上へのファイルへの出入力手段がほしい。

**Comment by aks3g** [comment]
すいません。こちらそもそも対応させてませんでした。
ちょっとお時間もらいますが実装します。しばしお待ちを。

**Comment by aks3g** [comment]
下回りのライブラリまで変更を入れたので、library/lib/*.a の類の入れ替えも必要になりますが、
micropython側からSDカードアクセスができるようになりました。

お試しいただければと思います。

**Comment by yukota** [comment]
動作しました！
ありがとうございます！

一点だけ、Make内のIncludeですが
/packs/arm/CMSIS/Include
を指定していますが、AtmelStudioから持ってきたpacksは以下のようなディレクトリになっています。
/packs/arm/cmsis/5.0.1/CMSIS/Include
以下のようなシンボリックリンクを貼る必要がある旨をどこかに書いておいたほうが良いかと思います。
ln -s cmsis/5.0.1/CMSIS CMSIS
